### ISSUE TITLE
User Story 1: List of all Art Pieces

### ISSUE THREAD

**Issue by FrankSiyli** [Stephan-mit-Ph/my-gallery-app#1]
#### Value Proposition

**As an** art enthusiast

**I want to** see a list of all art pieces

**so that** I can get an overview of all art pieces.

#### Acceptance Criteria

- [ ] All art pieces are displayed as a list 🖼️
- [ ] Each art piece's image is displayed 🖼️
- [ ] Each art piece's title is displayed 🖼️
- [ ] Each art piece's artist is displayed 🖼️

#### Tasks

- [x] Fetch all art pieces with `SWR` in `pages/index.js`
- [x] Create the component `ArtPieces` to render a list
- [x] `ArtPieces` props: `pieces`
- [x] Create the component `ArtPiecePreview`
- [x] `ArtPiecePreview` props: `image`, `title`, `artist`
- [x] All acceptance criteria marked with 🖼️ are covered by component testing

**Comment by toshydev** [comment]
- useSWR

**Comment by toshydev** [comment]
### Loading and Error state

```function Character() {
  const { data, error, isLoading, isValidating } = useSWR(
    "https://swapi.dev/api/people/1"
  );

  if (error) return <div>failed to load</div>;
  if (isLoading) return <div>loading...</div>;

  // render data
  return (
    <div>
      <span role="img" aria-label={isValidating ? "Validating" : "Ready"}>
        {isValidating ? "🔄" : "✅"}
      </span>
      Hello {data.name}!
    </div>
  );
}```

**Comment by toshydev** [comment]
### Rendering
Work in `pages/art-pieces/index.js`
