### ISSUE TITLE
### User Story 3: Separate Pages and Navigation Bar

### ISSUE THREAD

**Issue by toshydev** [Stephan-mit-Ph/my-gallery-app#2]
#### Value Proposition

**As an** art enthusiast

**I want to** be able to switch between the spotlight and list view

**so that** I can navigate the app easier.

#### Acceptance Criteria

- [ ] A navigation link labeled "Spotlight" is displayed 🖼️
- [ ] A navigation link labeled "Pieces" is displayed 🖼️
- [ ] Clicking "Spotlight" shows the SpotlightPage
- [ ] Clicking "Pieces" shows the ArtPiecesPage

#### Tasks

- [ ] Move the data fetching logic to `pages/_app`
- [ ] Find a solution for global state handling to have the art pieces available on all pages
- [ ] Adapt the page `pages/index`: rename the function to `SpotlightPage` and have it render only the `Spotlight` component
- [ ] Create the page `pages/art-pieces/index` that renders the `ArtPieces` component
- [ ] Create the component `Navigation` that renders all navigation links
- [ ] Create the component `Layout` that renders the `Navigation` component
- [ ] Apply the `Layout` component in `pages/_app`
- [ ] All acceptance criteria marked with 🖼️ are covered by component testing

**Comment by toshydev** [comment]
- make fetching global with

**Comment by toshydev** [comment]
### State uplifting
Lift state up to `_app.js`.

**Comment by toshydev** [comment]
#13
