### ISSUE TITLE
User Story 2: Spotlight Piece

### ISSUE THREAD

**Issue by FrankSiyli** [Stephan-mit-Ph/my-gallery-app#4]
#### Value Proposition

**As an** art enthusiast

**I want to** see a spotlight piece

**so that** I can get inspirational highlights.

#### Acceptance Criteria

- [ ] One art piece is picked at random to show as a spotlight piece
- [ ] The art piece image is displayed 🖼️
- [ ] The art piece artist is displayed 🖼️

#### Tasks

- [ ] Write function to pick one art piece [at random](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random#examples)
- [ ] Create the component `Spotlight`
- [ ] `Spotlight` props: `image`, `artist`
- [ ] All acceptance criteria marked with 🖼️ are covered by component testing

**Comment by Stephan-mit-Ph** [comment]
- Fetch Data
- Component with props (image, artist)
