### ISSUE TITLE
User Story 6: Favorite Listing Page

### ISSUE THREAD

**Issue by FrankSiyli** [Stephan-mit-Ph/my-gallery-app#7]
#### Value Proposition

**As an** art enthusiast

**I want to** see a comprehensive list of all my favorite art pieces

**so that** I can have an overview of all of my favorites.

#### Acceptance Criteria

- [ ] A navigation link labeled "Favorites" is displayed 🖼️
- [ ] Clicking the "Favorites" shows the FavoritesPage
- [ ] All favorite art pieces are displayed as a list 🖼️
- [ ] Each art piece's image is displayed 🖼️
- [ ] Each art piece's title is displayed 🖼️
- [ ] Each art piece's artist is displayed 🖼️
- [ ] Each art piece's is displayed with active favorite-button 🖼️

#### Tasks

- [ ] Create the page `pages/favorites` that renders the `ArtPieces` component
- [ ] Use data from the `artPiecesInfo` state to filter for all favorite art pieces
- [ ] Pass the list of all favorite art pieces via prop `pieces` to the `ArtPieces` component
- [ ] All acceptance criteria marked with 🖼️ are covered by component testing

**Comment by toshydev** [comment]
### Dependencies
Issues #3
